server:
  servlet:
    context-path: /zhihu
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.102.60.119/zhihu?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
  redis:
    database: 0
    host: 39.102.60.119
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 1
    timeout: 3000

  mail:
    host: smtp.163.com
    username: uzi244177153@163.com
    password: MFNLHQDWLXCWJNMH
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 25
          auth: true
          ssl:
            enable: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

web:
  upload-path: static/img/
  url: http://39.102.60.119:8080
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  config: classpath:logback-spring.xml
  file:
    path: /root/mylog/zhihu
  level:
    com.yidong.zhihu.mapper: debug


  profiles:
    active: pro